import Head from 'next/head'

import React, { useRef, Suspense } from "react";
import {
  useGLTF,
  OrbitControls,
  Environment,
  ContactShadows,
} from "@react-three/drei";
import { Canvas, useFrame } from "@react-three/fiber";


export function Sword(props) {
  const ref = useRef()

  const { nodes, materials } = useGLTF('/sword-lower-res-compressed.glb')

  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    ref.current.rotation.z = -0.2 - (1 + Math.sin(t / 1.5)) / 20
    ref.current.rotation.x = Math.cos(t / 4) / 8
    ref.current.rotation.y = Math.sin(t / 4) / 8
    ref.current.position.y = (1 + Math.sin(t / 1.5)) / 10
  })

  return (
    <group {...props} dispose={null} ref={ref}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.08, 0]}>
            <mesh geometry={nodes.pPlane1_phong1_0.geometry} material={materials.phong1} />
          </group>
          <mesh geometry={nodes.pPlane5_phong1_0.geometry} material={materials.phong1} />
          <group position={[12.55, 0.26, 0]}>
            <mesh geometry={nodes.polySurface2_phong1_0.geometry} material={materials.phong1} />
          </group>
          <mesh geometry={nodes.polySurface5_phong1_0.geometry} material={materials.phong1} />
          <mesh geometry={nodes.polySurface4_phong1_0.geometry} material={materials.phong1} />
          <group position={[9.11, 0, 0]}>
            <mesh geometry={nodes.pCube1_phong1_0.geometry} material={materials.phong1} />
          </group>
          <mesh geometry={nodes.pPlane4_phong1_0.geometry} material={materials.phong1} />
        </group>
      </group>
    </group>
  )
}

export default function Home() {

  return (
    <div className="container"><Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

      <Canvas camera={{ position: [0, 40, 20], fov: 40 }}>
        <ambientLight intensity={0.7} />
        <spotLight intensity={0.5} angle={0.1} penumbra={1} position={[10, 15, 10]} castShadow />

        <Suspense fallback={null}>
          <Sword />
          <Environment files="autumn-forest-1k.hdr" />
        </Suspense>
        <OrbitControls />
      </Canvas>
    </div>
  )
}
